version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - goconst
    - gosec
    # HTTP/API client specific
    - bodyclose
    - noctx
    # Error handling
    - errorlint
    - nilerr
    # Code quality
    - unconvert
    - prealloc
    - revive
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
